#!/bin/bash
#
# Provision agent with zero-touch token exchange
#
# Usage (production - systemd + D-Bus):
#   ./provision-agent.sh --token "<provisioning-jwt>" --cluster "<cluster-id>" --api-url "https://api.internal:4000"
#
# Usage (dev/macOS - local file output):
#   ./provision-agent.sh --token "<provisioning-jwt>" --cluster "<cluster-id>" --api-url "http://localhost:4000" --dev-local
#
# Environment:
#   CORE_API_URL: Override API URL (default: http://localhost:4000)
#   AGENT_HOME: Override agent directory (default: /opt/sustainabuild-agent or .dev-agent)

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROVISIONING_TOKEN=""
CLUSTER_ID=""
API_URL="${CORE_API_URL:-http://localhost:4000}"
DEV_LOCAL=false
: "${AGENT_HOME:=}"  # Allow env var override
LEASE_TTL_SECONDS="${LEASE_TTL_SECONDS:-3600}"

# Functions
log_info() {
  echo -e "${BLUE}[provision]${NC} $*"
}

log_success() {
  echo -e "${GREEN}[provision]${NC} $*"
}

log_error() {
  echo -e "${RED}[provision]${NC} $*" >&2
}

show_usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

OPTIONS:
  --token <TOKEN>              Provisioning JWT token (required)
  --cluster <CLUSTER_ID>       Cluster ID (required)
  --api-url <URL>              Core API URL (default: http://localhost:4000)
  --dev-local                  Dev mode: write to .dev-agent instead of /opt (for macOS/dev)
  --help                       Show this help message

EXAMPLES:
  # Production (Linux with systemd):
  $0 --token "eyJ..." --cluster "c1" --api-url "https://api.internal:4000"

  # Development (macOS/local):
  $0 --token "eyJ..." --cluster "c1" --api-url "http://localhost:4000" --dev-local

EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --token)
      PROVISIONING_TOKEN="$2"
      shift 2
      ;;
    --cluster)
      CLUSTER_ID="$2"
      shift 2
      ;;
    --api-url)
      API_URL="$2"
      shift 2
      ;;
    --dev-local)
      DEV_LOCAL=true
      shift
      ;;
    --help)
      show_usage
      exit 0
      ;;
    *)
      log_error "Unknown option: $1"
      show_usage
      exit 1
      ;;
  esac
done

# Validate arguments
if [ -z "$PROVISIONING_TOKEN" ]; then
  log_error "Missing required argument: --token"
  show_usage
  exit 1
fi

if [ -z "$CLUSTER_ID" ]; then
  log_error "Missing required argument: --cluster"
  show_usage
  exit 1
fi

# Determine agent home directory
if [ "$DEV_LOCAL" = true ]; then
  AGENT_HOME="${AGENT_HOME:-./.dev-agent}"
else
  AGENT_HOME="${AGENT_HOME:-/opt/sustainabuild-agent}"
fi

log_info "Provisioning agent for cluster: $CLUSTER_ID"
log_info "Agent home: $AGENT_HOME"
log_info "API URL: $API_URL"

# Create agent directory
if ! mkdir -p "$AGENT_HOME"; then
  log_error "Failed to create agent directory: $AGENT_HOME"
  exit 1
fi

# Step 1: Exchange provisioning token for device JWT
log_info "Exchanging provisioning token for device JWT..."

EXCHANGE_RESPONSE=$(curl -s -X POST "$API_URL/graphql" \
  -H 'Content-Type: application/json' \
  -d "{\"query\":\"mutation { exchangeProvisioningToken(provisioningToken:\\\"$PROVISIONING_TOKEN\\\") { deviceJwt clusterId } }\"}")

# Check for errors
if echo "$EXCHANGE_RESPONSE" | grep -q '"errors"'; then
  log_error "Failed to exchange provisioning token:"
  echo "$EXCHANGE_RESPONSE" | jq .
  exit 1
fi

# Extract device JWT and cluster ID
DEVICE_JWT=$(echo "$EXCHANGE_RESPONSE" | jq -r '.data.exchangeProvisioningToken.deviceJwt')
EXCHANGED_CLUSTER_ID=$(echo "$EXCHANGE_RESPONSE" | jq -r '.data.exchangeProvisioningToken.clusterId')

if [ -z "$DEVICE_JWT" ] || [ "$DEVICE_JWT" = "null" ]; then
  log_error "Failed to extract device JWT from response"
  exit 1
fi

if [ "$EXCHANGED_CLUSTER_ID" != "$CLUSTER_ID" ]; then
  log_error "Cluster ID mismatch: expected $CLUSTER_ID, got $EXCHANGED_CLUSTER_ID"
  exit 1
fi

log_success "Device JWT exchanged successfully"

# Step 2: Write agent configuration
AGENT_ENV="$AGENT_HOME/agent.env"
log_info "Writing agent configuration to: $AGENT_ENV"

cat > "$AGENT_ENV" <<ENV_EOF
# Generated by provision-agent.sh on $(date -u +'%Y-%m-%d %H:%M:%S UTC')
# Cluster ID
CLUSTER_ID="$CLUSTER_ID"

# Device JWT for authentication
DEVICE_JWT="$DEVICE_JWT"

# Core API URL
CORE_API_URL="$API_URL"

# Lease configuration
LEASE_TTL_SECONDS="$LEASE_TTL_SECONDS"

# Agent runtime settings
AGENT_MODE="device"  # device mode uses DEVICE_JWT for auth
DEV_LOCAL="$DEV_LOCAL"
ENV_EOF

chmod 600 "$AGENT_ENV"
log_success "Agent configuration written"

# Step 3: Production setup (systemd + D-Bus)
if [ "$DEV_LOCAL" = false ]; then
  log_info "Setting up systemd service and D-Bus permissions..."
  
  # Create systemd service file
  SYSTEMD_SERVICE="/etc/systemd/system/sustainabuild-agent.service"
  if [ ! -f "$SYSTEMD_SERVICE" ]; then
    log_info "Creating systemd service: $SYSTEMD_SERVICE"
    sudo tee "$SYSTEMD_SERVICE" > /dev/null <<SYSTEMD_EOF
[Unit]
Description=SustainaBuild IoT Agent
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
User=sustainabuild-agent
WorkingDirectory=$AGENT_HOME
EnvironmentFile=$AGENT_ENV
ExecStart=/usr/local/bin/sustainabuild-agent
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
SYSTEMD_EOF
    sudo systemctl daemon-reload
    log_success "Systemd service created"
  fi

  # Create D-Bus permissions
  DBUS_CONF="/etc/dbus-1/system.d/sustainabuild-agent.conf"
  if [ ! -f "$DBUS_CONF" ]; then
    log_info "Creating D-Bus permissions: $DBUS_CONF"
    sudo tee "$DBUS_CONF" > /dev/null <<DBUS_EOF
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy user="sustainabuild-agent">
    <allow send_destination="org.freedesktop.systemd1"
           send_interface="org.freedesktop.systemd1.Manager"
           send_member="SetDefaultTarget"/>
    <allow send_destination="org.freedesktop.systemd1"
           send_interface="org.freedesktop.systemd1.Manager"
           send_member="StartUnit"/>
    <allow send_destination="org.freedesktop.systemd1"
           send_interface="org.freedesktop.systemd1.Manager"
           send_member="StopUnit"/>
  </policy>
</busconfig>
DBUS_EOF
    log_success "D-Bus permissions created"
  fi

  log_info "To start the agent, run:"
  echo "  sudo systemctl start sustainabuild-agent"
  echo "  sudo systemctl enable sustainabuild-agent"
  log_info "To view logs:"
  echo "  sudo journalctl -u sustainabuild-agent -f"

else
  # Development mode
  log_success "Dev mode: Agent configuration ready"
  log_info "To verify the device JWT:"
  echo "  cat $AGENT_ENV | grep DEVICE_JWT"
  log_info "To start the agent in dev mode:"
  echo "  source $AGENT_ENV"
  echo "  pnpm --filter=@sustainabuild/agent run dev"

fi

log_success "Provisioning complete!"
echo ""
echo "Agent home: $AGENT_HOME"
echo "Configuration: $AGENT_ENV"
